apiVersion: v1
kind: Namespace
metadata:
  name: ptg
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptg-nominacao-v2
  namespace: ptg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ptg-nominacao-v2
  template:
    metadata:
      labels:
        app: ptg-nominacao-v2
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: ptg-nominacao-v2
        image: acrtbg.azurecr.io/ptg-nominacao-v2:TAG_REPLACE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: ptg-http
        - containerPort: 9090
          name: grpc-tcp
        envFrom:
        - secretRef:
            name: ptg-nominacao-secret
        - configMapRef:
            name: ptg-nominacao-configmap
        # livenessProbe:
#   httpGet:
#     path: /ptg-operacao/api/actuator/health
#     port: ptg-http
#   initialDelaySeconds: 120
#   periodSeconds: 10
#   failureThreshold: 3
#   timeoutSeconds: 1
#   successThreshold: 1
# readinessProbe:
#   httpGet:
#     path: /ptg-operacao/api/actuator/health
#     port: ptg-http
#   timeoutSeconds: 1
#   periodSeconds: 10
#   successThreshold: 1
#   failureThreshold: 3
#   initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ptg-nominacao-v2-srv
  namespace: ptg
spec:
  type: ClusterIP
  ports:
  - targetPort: 8080
    name: http-svc
    port: 80
    protocol: TCP
  - targetPort: 9090
    name: grpc-svc
    port: 90
    protocol: TCP
  selector:
    app: ptg-nominacao-v2
