apiVersion: v1
kind: Service
metadata:
  name: spr-nominacao-service
spec:
  selector:
    app: spr-nominacao-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8020
  type: LoadBalancer