apiVersion: v1
kind: ConfigMap
metadata:
  name: ptg-flyway-operacao-configmap
  namespace: ptg
data:
  FLYWAY_BASELINEVERSION: '202402291330'
  FLYWAY_URL: jdbc:sqlserver://ptgqa.database.windows.net:1433;database=ptg;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

---
apiVersion: v1
kind: Secret
metadata:
  name: ptg-flyway-operacao-secret
  namespace: ptg
type: Opaque
data:
  FLYWAY_PASSWORD: REItMmNkOCNIdFkmeGtmZCFLbXQtd1Jz
  FLYWAY_USER: YWRtc3FscHRncWE=
