apiVersion: v1
kind: Secret
metadata:
  name: ptg-nominacao-secret
  namespace: ptg
type: Opaque
data:
  PTG_DATASOURCE_PASSWORD: "SGFNTUA3NDkyI0dHZVU="
  PTG_DATASOURCE_USER: "YXBwX3B0Z19ub21pbmFjYW8="
  PTG_NOMINACAO_JMS_CONNECTION_PASSWORD: "UVc1WTlIOUJBYnVSK1d4cDh1dk9UNnV3bTA4eE5TWDRBK0FTYkdvc0trTT0="